DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS filme;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE filme (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    titulo TEXT NOT NULL,
    genero TEXT NOT NULL,
    ano INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);